# Generated by Django 3.0 on 2020-10-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=1, verbose_name='позиция'),
            preserve_default=False,
        ),
    ]
