# Generated by Django 3.0 on 2021-05-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20201004_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(db_index=True, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Заголовок'),
        ),
    ]
